### Versión de Ubuntu
FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y build-essential \
	nano \
	man \
	sudo \
	openssh-server \
	sshpass

### Instalo BLAS, LAPACK, ATLAS y R

RUN sudo apt-get install libblas-dev libblas3 libatlas-base-dev\
 libatlas3-base libblas-test libblasr libblasr-dev libopenblas-base\
 libopenblas-dev r-base

### Instalo paqueterías necesarias para R-benchmark-25.R 
RUN echo "install.packages('SuppDists', dep=TRUE, repo='http://cran.stat.ucla.edu')" |\
 sudo R --vanilla 

### Copio los scrips que tengo en mi carpeta
COPY . /scripts/TripleF_benchmark.R
COPY . /scripts/R-benchmark-25.R




